sudo: required

language: python

python:
  - "2.7"
  - "3.6"

cache: pip

install:
  - pip install pipenv
  - export PIPENV_IGNORE_VIRTUALENVS=1
  - pipenv install --dev

script:
  - pipenv run pytest

branches:
  only:
  - master
  - dev

notifications:
  email: false

matrix:
    fast_finish: true
    include:
      - env: LINT_CHECK
        python: "2.7"
        install: pip install flake8
        script: flake8
      - env: LINT_CHECK
        python: "3.7"
        dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
        sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
        install: pip install flake8
        script: flake8